version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - app-network

  user-api:
    image: fatecstore/user-api:20250412.1
    container_name: user-api
    ports:
      - "8080:8080"
    environment:
      - AppsettingsConfigurations__EmailConfiguration__FromMail=fatec.store2025@gmail.com
      - AppsettingsConfigurations__EmailConfiguration__FromMailPassword=hvkmxsqkzvjnmlim
      - AppsettingsConfigurations__JwtConfiguration__Audience=TesteAudience
      - AppsettingsConfigurations__JwtConfiguration__Issuer=TesteIssuer
      - AppsettingsConfigurations__JwtConfiguration__SecretJwtKey=YjA2Nzk0MmJjMTUyNDgyNThhY2NmOWNlNmZkMDg2NDFhdXRodGVzdGU=
      - AppsettingsConfigurations__RedisConfiguration__ExpirationInMinutes=60
      - AppsettingsConfigurations__RedisConfiguration__Server=redis:6379
      - AppsettingsConfigurations__Database=Server=store.cdgy200a0n54.sa-east-1.rds.amazonaws.com,1433;Initial Catalog=Store;User ID=SA;Password=*SQLestudo2024;Encrypt=False;TrustServerCertificate=False;Connection Timeout=30;
    depends_on:
      - redis
    networks:
      - app-network

  products-api:
    image: fatecstore/products-api:20250412.2
    container_name: products-api
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=store.cdgy200a0n54.sa-east-1.rds.amazonaws.com,1433;Initial Catalog=Store;User ID=SA;Password=*SQLestudo2024;Encrypt=False;TrustServerCertificate=False;Connection Timeout=30;
    depends_on:
      - redis
    networks:
      - app-network
 
  carts-api:
    image: fatecstore/carts-api:20250412.2
    container_name: carts-api
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=store.cdgy200a0n54.sa-east-1.rds.amazonaws.com,1433;Initial Catalog=Store;User ID=SA;Password=*SQLestudo2024;Encrypt=False;TrustServerCertificate=False;Connection Timeout=30;
    depends_on:
      - redis
    networks:
      - app-network

  store-web:
    image: fatecstore/web:latest
    container_name: store-web
    depends_on:
      - products-api
      - user-api 
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge